### ISSUE TITLE
DataFormat 

### ISSUE THREAD

**Issue by ibrahimsharif** [Microsoft/Intune-Data-Warehouse#7]
Recived Data From Device collection, Data Format are not Formatet correctly   
 
This Lines are from the Powershell Module 
  
    "startDateInclusiveUTC":  "2017-10-16T00:00:00Z",
    "endDateExclusiveUTC":  "9999-12-31T00:00:00Z",
    "isCurrent":  true,
    "rowLastModifiedDateTimeUTC":  "2017-10-17T00:24:11.8233333Z",
--------------------------------------------------------------------------------------------------------    

this is how the date shold  appear

![image](https://user-images.githubusercontent.com/24541271/31724196-5b9226d2-b421-11e7-8a3e-3d57652afb7a.png)

Sorry my Broken Englsih 🔢  :)

**Comment by nickciaravella** [comment]
Hey Ibrahim,

Dates and times that are returned from the API are represented as strings, since JSON has no DateTime type. In PowerShell, you can convert these to any format by first parsing the string into a DateTime object, then converting it back to a string with your preferred format specifier. Here is an example to get the string into the format that Power BI Is displaying in your screenshot above.

```powershell
$dateTime = [datetime]::parse("2017-10-16T00:00:00Z")
$dateTime.ToString("g")
10/15/2017 5:00 PM
```

Here are more details on the possible format specifiers:
Standard: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings
Custom: https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

Another thing to note is that all times returned are in UTC time, not your local time zone. To convert a DateTime object from UTC to your local time zone, you can use the function in this blog post: https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/01/powertip-convert-from-utc-to-my-local-time-zone/

Let me know if this solves your issue!

**Comment by ibrahimsharif** [comment]
Nice Thanks, 
i did as below and it works jubii 
[datetime]::parse("2017-10-16T00:00:00Z").Tostring('MM/dd/yy HH:mm:ss')

have a greate day, your are my hero today

**Comment by nickciaravella** [comment]
Excellent! Glad it worked for you.
